import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { openDatabase } from '../src/db/index.js';
import { Budget, freshness } from '../src/services/budget.js';
import { discovery, product, reviewPage, installFloor } from '../src/normalize/index.js';
import { saveDiscovery, saveDetail, saveReviews, runWithItems, log } from '../src/services/store.js';
const fixture = name => JSON.parse(readFileSync(new URL(`./fixtures/${name}.json`,import.meta.url)));
const fresh = () => openDatabase(':memory:');
const loc = {country:'US',language:'en'};
test('chart rank, search position, nullable fields and duplicate source observations', () => {
 const db=fresh(); const p={kind:'chart',...loc,categoryId:'PRODUCTIVITY',chart:'topselling_free'};
 const chart=discovery(fixture('chart'),'chart'); const first=saveDiscovery(db,p,chart); const second=saveDiscovery(db,p,chart);
 assert.equal(first.run.id,second.run.id); assert.equal(second.repeated,true);
 assert.equal(first.run.items[0].chart_rank,1); assert.equal(first.run.items[1].rating,null);
 const search=saveDiscovery(db,{kind:'search',...loc,keyword:'alpha'},discovery(fixture('search'),'search'));
 assert.equal(search.run.items[0].section,'Recommended'); assert.equal(search.run.items[0].chart_rank,null);
 assert.equal(db.prepare('SELECT COUNT(*) n FROM app_snapshots WHERE package_id=?').get('com.example.alpha').n,2);
 assert.equal(freshness(db,'chart',p).fresh,true);
 db.close();
});
test('product and review deduplication, compatible rank context', () => {
 const db=fresh(),p={packageId:'com.example.alpha',...loc};
 saveDiscovery(db,{kind:'chart',...loc,categoryId:'PRODUCTIVITY',chart:'topselling_free'},discovery(fixture('chart'),'chart'));
 const item=product(fixture('product'));
 assert.equal(item.released_on_text,'Jan 5, 2020');
 assert.equal(item.content_rating_text,'Everyone');
 assert.equal(JSON.parse(item.product_metadata_json).developerContact.supportEmail,'help@example.test');
 saveDetail(db,p,item); saveDetail(db,p,item);
 assert.equal(db.prepare("SELECT COUNT(*) n FROM app_snapshots WHERE package_id=? AND source_type='product'").get(p.packageId).n,1);
 const page=reviewPage(fixture('reviews')); saveReviews(db,{...p,rating:1,sort:1},page,null); saveReviews(db,{...p,rating:1,sort:1},page,null);
 assert.equal(db.prepare('SELECT COUNT(*) n FROM reviews').get().n,2);
 assert.equal(db.prepare('SELECT COUNT(*) n FROM review_fetches').get().n,1);
 const ranks=db.prepare("SELECT COUNT(*) n FROM discovery_items i JOIN discovery_runs r ON i.run_id=r.id WHERE i.chart_rank IS NOT NULL AND r.country='IN'").get().n;
 assert.equal(ranks,0);
 const inChart=fixture('chart');inChart.search_metadata.id='chart-in';
 saveDiscovery(db,{kind:'chart',country:'IN',language:'en',categoryId:'PRODUCTIVITY',chart:'topselling_free'},discovery(inChart,'chart'));
 const usRanks=db.prepare("SELECT COUNT(*) n FROM discovery_items i JOIN discovery_runs r ON i.run_id=r.id WHERE i.package_id='com.example.alpha' AND i.chart_rank IS NOT NULL AND r.country='US' AND r.language='en' AND r.category_id='PRODUCTIVITY' AND r.chart='topselling_free'").get().n;
 assert.equal(usRanks,1);
 assert.equal(installFloor('10B+'),10000000000); db.close();
});
test('budget guard: local hit, floor, unavailable status, free provider cache', async () => {
 const db=fresh(),p={kind:'chart',...loc,categoryId:'PRODUCTIVITY',chart:'topselling_free'};
 const provider={getAccount:async()=>({searches_per_month:250,this_month_usage:229,plan_searches_left:21,plan_renewal_date:null})};
 const budget=new Budget(db,provider,20);
 assert.equal((await budget.preview('chart',p)).allowed,true);
 let calls=0;
 await budget.run('chart','chart',p,1,async call=>{calls++; return call(async()=>fixture('chart'));});
 await assert.rejects(()=>budget.run('second','review',{...p,pages:2},2,async()=>{calls++;}));
 assert.equal(calls,1);
 saveDiscovery(db,p,{...discovery(fixture('chart'),'chart'),observedAt:new Date().toISOString()});
 assert.equal((await budget.preview('chart',p)).possibleCost,0);
 const unavailable=new Budget(db,{getAccount:async()=>{throw new Error('offline');}},20);
 assert.equal((await unavailable.preview('review',{pages:1})).allowed,false);
 await assert.rejects(()=>unavailable.run('x','review',{},1,async()=>{}));
 assert.equal(db.prepare("SELECT COUNT(*) n FROM api_requests WHERE outcome='success'").get().n,1);
 db.close();
});
